apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "random-log-generator.fullname" . }}-config
  labels:
    {{- include "random-log-generator.labels" . | nindent 4 }}
data:
  config.yaml: |
    log_rate: {{ .Values.config.logRate }}
    log_levels:
      {{- range .Values.config.logLevels }}
      - {{ . }}
      {{- end }}
    output:
      type: {{ .Values.config.outputType }}
      path: {{ .Values.config.outputPath }}
      rotation:
        size: {{ .Values.config.rotationSize }}
        count: {{ .Values.config.rotationCount }}
    format:
      type: {{ .Values.config.format }}
      {{- if eq .Values.config.format "custom" }}
      custom_format: {{ .Values.config.customFormat }}
      {{- end }}