name: Docker and Helm CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          load: true
          tags: random-log-generator:test
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Test Docker image
        run: |
          docker run --rm random-log-generator:test --version
          # Create a test config file
          echo "log_rate: 5" > test-config.yaml
          echo "log_levels:" >> test-config.yaml
          echo "  - INFO" >> test-config.yaml
          echo "  - ERROR" >> test-config.yaml
          echo "output:" >> test-config.yaml
          echo "  type: console" >> test-config.yaml
          echo "  path: /app/logs/test.log" >> test-config.yaml
          echo "format:" >> test-config.yaml
          echo "  type: http" >> test-config.yaml
          
          # Run the container with the test config for a short time
          timeout 5s docker run --rm -v $(pwd)/test-config.yaml:/app/config.yaml random-log-generator:test --config config.yaml || code=$?
          if [ $code -eq 124 ]; then
            echo "Container ran successfully and was terminated after timeout"
            exit 0
          else
            echo "Container exited with unexpected code: $code"
            exit 1
          fi

  helm-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: 'v3.10.0'

      - name: Lint Helm chart
        run: |
          helm lint ./helm/random-log-generator

  helm-test:
    runs-on: ubuntu-latest
    needs: [docker-build, helm-lint]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          load: true
          tags: random-log-generator:test
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: 'v3.10.0'

      - name: Create kind cluster
        uses: helm/kind-action@v1.5.0
        with:
          cluster_name: kind-test

      - name: Load Docker image into kind
        run: |
          kind load docker-image random-log-generator:test --name kind-test

      - name: Install Helm chart
        run: |
          # Update the values file to use the local image
          sed -i 's/repository: random-log-generator/repository: random-log-generator\n  tag: test/' ./helm/random-log-generator/values.yaml
          
          # Install the chart
          helm install test-release ./helm/random-log-generator
          
          # Wait for the pod to be ready
          kubectl wait --for=condition=ready pod -l app.kubernetes.io/name=random-log-generator --timeout=60s
          
          # Get pod name
          POD_NAME=$(kubectl get pods -l app.kubernetes.io/name=random-log-generator -o jsonpath="{.items[0].metadata.name}")
          
          # Check pod logs to verify it's running
          kubectl logs $POD_NAME
          
          # Verify the ConfigMap exists
          kubectl get configmap test-release-random-log-generator-config
          
          # Clean up
          helm delete test-release